# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-08-13 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='contact/images/%Y-%m-%d')),
                ('date', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='home/images/%Y-%m-%d')),
                ('date', models.DateField(default='')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HomeParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='home/images/%Y-%m-%d')),
                ('date', models.DateField(default='')),
                ('category', models.CharField(choices=[('STAINED', 'Stained'), ('ETCHED', 'Etched'), ('FACETED', 'Faceted')], max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
