# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_homeparagraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='wide_image',
            field=models.ImageField(default='', upload_to='home/images/%Y-%m-%d'),
        ),
    ]
